ALTER TABLE public."Users"
  ADD COLUMN IF NOT EXISTS "GoCardlessConnected" boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS "GoCardlessOrganisationId" text,
  ADD COLUMN IF NOT EXISTS "GoCardlessConnectionStatus" text,
  ADD COLUMN IF NOT EXISTS "GoCardlessLastSyncAt" timestamptz;

ALTER TABLE public."Customers"
  ADD COLUMN IF NOT EXISTS "GoCardlessCustomerId" text,
  ADD COLUMN IF NOT EXISTS "GoCardlessCustomerBillingDetailId" text,
  ADD COLUMN IF NOT EXISTS "GoCardlessMandateId" text,
  ADD COLUMN IF NOT EXISTS "GoCardlessMandateStatus" text,
  ADD COLUMN IF NOT EXISTS "GoCardlessMandateLastEventAt" timestamptz,
  ADD COLUMN IF NOT EXISTS "GoCardlessBillingRequestId" text,
  ADD COLUMN IF NOT EXISTS "GoCardlessBillingRequestFlowId" text;

ALTER TABLE public."CustomerInvoices"
  ADD COLUMN IF NOT EXISTS "GoCardlessBillingRequestId" text,
  ADD COLUMN IF NOT EXISTS "GoCardlessBillingRequestFlowId" text,
  ADD COLUMN IF NOT EXISTS "GoCardlessPaymentId" text,
  ADD COLUMN IF NOT EXISTS "GoCardlessPaymentStatus" text,
  ADD COLUMN IF NOT EXISTS "GoCardlessRequestedAt" timestamptz;

CREATE TABLE IF NOT EXISTS public."GoCardlessConnections" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" bigint NOT NULL UNIQUE,
  "OrganisationId" text NOT NULL UNIQUE,
  "AccessToken" text NOT NULL,
  "Environment" text NOT NULL DEFAULT 'sandbox',
  "ConnectedAt" timestamptz NOT NULL DEFAULT now(),
  "DisconnectedAt" timestamptz,
  "LastError" text,
  "UpdatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."GoCardlessWebhookEvents" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "EventId" text NOT NULL UNIQUE,
  "OrganisationId" text,
  "ResourceType" text,
  "Action" text,
  "Payload" jsonb,
  "ProcessedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS gocardless_connections_user_id_idx
  ON public."GoCardlessConnections" ("UserId");

CREATE INDEX IF NOT EXISTS gocardless_connections_organisation_id_idx
  ON public."GoCardlessConnections" ("OrganisationId");

CREATE INDEX IF NOT EXISTS gocardless_webhook_events_event_id_idx
  ON public."GoCardlessWebhookEvents" ("EventId");
