-- Store external (off-system) invoice clients so their details can be reused
CREATE TABLE IF NOT EXISTS public."ExternalClients" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" bigint NOT NULL,
  "ClientName" text NOT NULL,
  "ClientAddress" text,
  "CreatedAt" timestamptz NOT NULL DEFAULT now(),
  "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
  UNIQUE ("UserId", "ClientName")
);

CREATE INDEX IF NOT EXISTS external_clients_user_id_idx ON public."ExternalClients" ("UserId");
