ALTER TABLE public."Users"
  ADD COLUMN IF NOT EXISTS "TwilioConnected" boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS "TwilioPhoneNumber" text,
  ADD COLUMN IF NOT EXISTS "TwilioConnectionStatus" text,
  ADD COLUMN IF NOT EXISTS "TwilioLastSyncAt" timestamptz;

CREATE TABLE IF NOT EXISTS public."TwilioConnections" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" bigint NOT NULL UNIQUE,
  "AccountSid" text NOT NULL UNIQUE,
  "AuthToken" text NOT NULL,
  "FromNumber" text NOT NULL,
  "BillingRatePencePerSegment" integer NOT NULL DEFAULT 5,
  "ConnectedAt" timestamptz NOT NULL DEFAULT now(),
  "DisconnectedAt" timestamptz,
  "LastError" text,
  "UpdatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."TwilioWallets" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" bigint NOT NULL UNIQUE,
  "BalancePence" bigint NOT NULL DEFAULT 0,
  "Currency" text NOT NULL DEFAULT 'GBP',
  "UpdatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."TwilioWalletTransactions" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" bigint NOT NULL,
  "CustomerId" bigint,
  "MessageSid" text,
  "EntryType" text NOT NULL,
  "AmountPence" bigint NOT NULL,
  "BalanceAfterPence" bigint,
  "Description" text,
  "CreatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."TwilioMessageLogs" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" bigint NOT NULL,
  "CustomerId" bigint,
  "ToNumber" text,
  "FromNumber" text,
  "Body" text,
  "Status" text,
  "TwilioMessageSid" text UNIQUE,
  "SegmentCount" integer,
  "CostPence" bigint,
  "Provider" text NOT NULL DEFAULT 'twilio',
  "SentAt" timestamptz NOT NULL DEFAULT now(),
  "DeliveredAt" timestamptz,
  "Error" text,
  "Payload" jsonb
);

CREATE INDEX IF NOT EXISTS twilio_connections_user_id_idx
  ON public."TwilioConnections" ("UserId");

CREATE INDEX IF NOT EXISTS twilio_wallets_user_id_idx
  ON public."TwilioWallets" ("UserId");

CREATE INDEX IF NOT EXISTS twilio_wallet_transactions_user_id_idx
  ON public."TwilioWalletTransactions" ("UserId");

CREATE INDEX IF NOT EXISTS twilio_message_logs_user_id_idx
  ON public."TwilioMessageLogs" ("UserId");
